server.port: 8090 # tomcat server port:8090 set

spring:
  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 423794899259-v1u4c59oie7dhmhmnbeuh2ta0fjun841.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile
    user: # initial name & password
      name: user
      password: 1234
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb # mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
      encoding: utf-8
  devtools:
    livereload:
      enabled: true

mybatis:
  mapper-locations: mybatis-mapper/**/*-sql.xml # mapper.xml
  configuration:
    map-underscore-to-camel-case: true # camel case
  # xml에 있는 모델 앞의 패키지명을 생략 가능하도록 지원해주는 기능
  type-aliases-package: com.anjxxyi.practice.boilerplate.model
